name: Build Windows 11 Executable

on:
  push:
    branches:
      - main  # 或者你想要触发工作流的分支

jobs:
  build:
    runs - on: windows - 2022  # 这对应Windows 11环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup - python@v5
        with:
          python - version: '3.10'  # 根据你的脚本选择合适的Python版本

      - name: Install dependencies
        run: |
          python - m pip install --upgrade pip
          pip install pyinstaller  # 安装打包工具
          pip install pandas openpyxl
          # 如果你的脚本有其他依赖，在此添加pip install [dependency]

      - name: Build executable
        run: |
          pyinstaller -F -n "excel处理" my_matching.py
          # -F表示生成单个可执行文件，-n指定生成的文件名，替换YourAppName为你想要的名字

      - name: Upload artifact
        uses: actions/upload - artifact@v4
        with:
          name: windows - exe
          path: dist/
